### ISSUE TITLE
Booting main firmware failed

### ISSUE THREAD

**Issue by Xaranar** [ikorb/gcvideo#26] opened 2020-01-14 17:46 UTC
Just flashed this onto my Wii using the specified fpgaconf file, and it boots into black and white with the error message "Booting main firmware failed!"

**Comment by ikorb** [comment] 2020-01-14 18:28
Ugh, I hate FPGAconf...

Can you please start the flash memory viewer by hitting the Z button on a Gamecube controller and send me a picture of the screen showing the hex dump starting at address 00000?

**Comment by Xaranar** [comment] 2020-01-14 19:27
I would love to, only hitting Z does nothing, nor does hitting any other button on the controller.

**Comment by Xaranar** [comment] 2020-01-14 19:39
![IMG_0828](https://user-images.githubusercontent.com/45008956/72376277-9ad16600-3705-11ea-9568-f7d94bf70d19.JPEG)
This is all I get, and no buttons change the OSD.

**Comment by ikorb** [comment] 2020-01-14 20:24
Ah! Yes, that's the one message in the code where I don't check the gamepad.

Unfortunately, I currently do not have an idea why this fails for you.

**Comment by Xaranar** [comment] 2020-01-14 20:26
Is there any chance you can link me to the version 3.0 you were able to get loading, and then I can update to 3.0a via the homebrew app?

**Comment by Xaranar** [comment] 2020-01-14 20:50
How frustrating.  Could you perhaps recommend a better way of programming if FPGAconf is so awful?

**Comment by ikorb** [comment] 2020-01-14 21:01
I'm not yet sure if the issue is actually caused by FPGAconf or something else - if you reach that screen, the flash update tool has verified the presence and correctness of the main firmware, but the FPGA refuses to accept the reboot command. I'm not sure yet how this can happen.

**Comment by Xaranar** [comment] 2020-01-14 21:11
Interesting.  Well, let me know if there is anything else I can do.

**Comment by ikorb** [comment] 2020-01-14 21:19
Give me a bit of time to think about it. I might ask you to flash one or more test builds that have additional debug messages, but I need to figure out what information I need to gather that way.

**Comment by Xaranar** [comment] 2020-01-14 21:21
Alrighty, well I'm happy to help in any way I can.

**Comment by kimbapslice** [comment] 2020-01-15 14:09
Hello, I am getting this issue as well tyring to flash 3.0a into a wiidual v1.1 board with what appears to be a MXIC 25L4006E chip. I have gotten to the flash memory viewer dump screen. I will take pictures of that after work.

**Comment by kimbapslice** [comment] 2020-01-15 14:12
I used the gcvideo wii dual bin build and a CH341A programmer.

**Comment by kimbapslice** [comment] 2020-01-15 17:13
I had to hold down the IR setup button on the wiidual while powering on to get to the firmware screen to get the hex dump to appear.

**Comment by kimbapslice** [comment] 2020-01-15 17:14
![IMG_20200115_120629488](https://user-images.githubusercontent.com/58018661/72455274-7c647c80-3790-11ea-9858-c68a8c9a5c32.jpg)

**Comment by kimbapslice** [comment] 2020-01-15 17:15
![IMG_20200115_120728326](https://user-images.githubusercontent.com/58018661/72455337-969e5a80-3790-11ea-8bde-e4cbfe5b2746.jpg)
![IMG_20200115_120739974](https://user-images.githubusercontent.com/58018661/72455359-a027c280-3790-11ea-88bf-a10168c6bae6.jpg)
![IMG_20200115_121018318](https://user-images.githubusercontent.com/58018661/72455371-a74ed080-3790-11ea-932f-adb43b459ee9.jpg)

**Comment by Shiftone** [comment] 2020-01-15 17:16
Are you using firmware from this repo or the ones Dan posted? http://dansprojects.com/firmware/WiiDual/

**Comment by kimbapslice** [comment] 2020-01-15 17:18
This is a flash of this repo's 3.0a bin for the Wii dual.
Having said that, I have the same issue after flashing Dan's 3.0a version as well.

**Comment by kimbapslice** [comment] 2020-01-15 17:20
I can/have tried flashing back Dan's version of 2.4.c2 and the Wii dual works normally after that.

**Comment by ikorb** [comment] 2020-01-15 19:32
@kimbapslice: Thanks for the screenshots, it looks like the flash content is correct. Since you use a Wii-Dual board and have the same problem as Xaranar, I fear it may be a Wii-specific problem. 

Unfortunately, I don't have a dismantled Wii available for testing right now, so for now the only solution I can offer is to re-flash with a previous version.

I'll try to set up a test system to figure this problem out as soon as possible, but please remember that this is just a hobby and free time is limited...

**Comment by kimbapslice** [comment] 2020-01-15 19:40
Hi ikorb,
I completely understand. Thank you for your continued great work on the new firmware feature set! My Carby and GCdual are happily running 3.0a. My technical skills end at just about here, so I will flash back to the working 2.4c2 version and patiently await for updates. The wii is such a pain to take apart with all the tiny screws. Please let me know if you need anything else such as more flash dump screens. Thanks again!

**Comment by ikorb** [comment] 2020-01-15 23:52
Just had a random idea what might cause the problem, test build attached. I think the chance of actually solving the problem that way is pretty low though.

[gcvideo-TEST-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4068297/gcvideo-TEST-dual-wii.zip)
[gcvideo-TEST-p2xh-wii-fpgaconf.zip](https://github.com/ikorb/gcvideo/files/4068298/gcvideo-TEST-p2xh-wii-fpgaconf.zip)

**Comment by kimbapslice** [comment] 2020-01-16 02:02
I tried your test bin with the same failed to boot firmware error. Please see the attached dump screens.

**Comment by kimbapslice** [comment] 2020-01-16 02:04
![IMG_20200115_205737067](https://user-images.githubusercontent.com/58018661/72486944-709da800-37da-11ea-8111-820efcb70221.jpg)
![IMG_20200115_210021561](https://user-images.githubusercontent.com/58018661/72486959-772c1f80-37da-11ea-8bf1-f55533d3264b.jpg)
![IMG_20200115_210030338](https://user-images.githubusercontent.com/58018661/72486973-80b58780-37da-11ea-85b0-fae58fdbdb08.jpg)
![IMG_20200115_210035168](https://user-images.githubusercontent.com/58018661/72486987-89a65900-37da-11ea-9d2f-91611a52ab7e.jpg)

**Comment by Xaranar** [comment] 2020-01-16 10:09
Only just seen this, I'm going to try your test this evening when I get home from work, although I'm not holding my breath since kimbapslice is still experiencing issues.  Thanks for all of your work on this, by the way, I know it's just a hobby for you and you're giving up your free time to help us, we really appreciate it.

**Comment by Xaranar** [comment] 2020-01-16 16:57
Okay, can confirm that I'm in the same position as kimbapslice, I have the exact same error message as was originally displayed to me.

**Comment by ikorb** [comment] 2020-01-18 21:48
Ok, I've got a Wii to develop with once more - (un)fortunately it boots the standard 3.0a release binaries without any issue, so it looks like more remote debugging for now.

Attached below is a new test build that should show various register contents for 30s before it attempts to boot the main firmware. It will most likely show the same error message as before, this is just for getting more data for diagnosis. Of course if it does happen to boot into the main firmware after the 30s delay, that would also be a very interesting result.

Please test and take a picture of the register dump - should display "Booting in XX second(s)" and something like "gen1_boot XXXX", "gen1 XXXX gen2 YYYY mode ZZZZ" and more below that.

[gcvideo-TEST-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4081808/gcvideo-TEST-dual-wii.zip)
[gcvideo-TEST-p2xh-wii.zip](https://github.com/ikorb/gcvideo/files/4081809/gcvideo-TEST-p2xh-wii.zip)

**Comment by kimbapslice** [comment] 2020-01-18 23:08
Still failed. Please see attached screenshots. It's a black Wii with GameCube ports, board revision CS 60. I have the basic priiloader and Homebrew channel installed. Would that cause an issue? Again 2.4 versions work even now if I flash it.
![IMG_20200118_180042522](https://user-images.githubusercontent.com/58018661/72671776-73d4a600-3a1d-11ea-93c9-e85005d8c180.jpg)
![IMG_20200118_180122343](https://user-images.githubusercontent.com/58018661/72671779-7afbb400-3a1d-11ea-858f-6af0faad0575.jpg)

**Comment by ikorb** [comment] 2020-01-19 01:39
Thanks!

The software on your Wii should not matter, it's purely an issue on the GCVideo side. In the FPGA there is a hardware module that is used to reboot the chip into a different configuration and judging from your screenshots it completely refuses to talk with my software. Unfortunately, that module is also very under-documented by the chip manufacturer and rarely used by other projects.

Another attempt attached, not sure yet what to try if that one also doesn't do anything.

(note for my own reference: primary DCM, Lck-Cycle 6, ConfigRate 1)

**Comment by kimbapslice** [comment] 2020-01-19 02:12
Yes, it booted into this. Weird colors though even after rebooting.
![IMG_20200118_210848647](https://user-images.githubusercontent.com/58018661/72673349-38df6c00-3a37-11ea-9497-a99065e42e89.jpg)
![IMG_20200118_210915038](https://user-images.githubusercontent.com/58018661/72673352-40067a00-3a37-11ea-9c02-ce14d60b2b22.jpg)
![IMG_20200118_210938506](https://user-images.githubusercontent.com/58018661/72673355-485eb500-3a37-11ea-9c2e-0e0ade36eb37.jpg)

**Comment by kimbapslice** [comment] 2020-01-19 02:27
I can access the full menu with controller and ir remote.
![IMG_20200118_212706407](https://user-images.githubusercontent.com/58018661/72673500-6200fc00-3a39-11ea-8621-2422dbca99ef.jpg)

**Comment by ikorb** [comment] 2020-01-19 11:47
Yay! The inverted colors are due to a change I forgot to add, that should be fixed in the test builds below.

This time there are three test builds, each with just a single change from the previous one. I hope it can be isolated to just a single change - if it happens to be in TEST2, I'll need you to try a few more builds before I can release a fixed version because that one really slows down the boot process.

(sorry, no p2xh builds this time)

[gcvideo-TEST1-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4082596/gcvideo-TEST1-dual-wii.zip)
[gcvideo-TEST2-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4082597/gcvideo-TEST2-dual-wii.zip)
[gcvideo-TEST3-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4082598/gcvideo-TEST3-dual-wii.zip)

**Comment by kimbapslice** [comment] 2020-01-19 14:50
Test1: nothing on the screen, does not boot, black screen. Blue diagnostic wiidual light blinks slowly.

Test2: boots, full colors, full menu
Test3: binary seems to be identical to Test2. Menu also says test2.
Screenshots are from test 2
![IMG_20200119_092907465](https://user-images.githubusercontent.com/58018661/72682971-15e9a200-3aa1-11ea-8c26-dadedee445ad.jpg)
![IMG_20200119_092933275](https://user-images.githubusercontent.com/58018661/72682974-1b46ec80-3aa1-11ea-8f05-db969f90f6c4.jpg)

**Comment by ikorb** [comment] 2020-01-19 15:20
The test3 failure was because I messed up during the manual build process - but since test2 works that's not a problem.

Attached is a version that increases boot speed again, but not to the original level. 3.0 was released with speed 17, the test2 build was 1 and the attached one is 10. If it works, I'll create a 3.0b release using that setting later today.

[gcvideo-TEST_C10-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4082833/gcvideo-TEST_C10-dual-wii.zip)

**Comment by kimbapslice** [comment] 2020-01-19 15:37
Test C10: black screen, doesn't boot, wiidual diagnostic light blinks slowly. Verified data on chip vs binary.

**Comment by kimbapslice** [comment] 2020-01-19 15:54
Test C10: 
At first black screen, doesn't boot, wiidual diagnostic light blinks slowly. Verified data on chip vs binary.

Then I flashed with test2, black screen blue blinking light. Verified data.

Then I flashed with "TEST3" binary, verified, Booted into full, correct color menu as before.

Flashed C10 again, verified data. Now "failed to boot into main firmware". Screenshots below are from C10 second flash.
![IMG_20200119_104956070](https://user-images.githubusercontent.com/58018661/72683921-0cb10300-3aaa-11ea-98f3-5a4a43fff799.jpg)
![IMG_20200119_105025534](https://user-images.githubusercontent.com/58018661/72683924-133f7a80-3aaa-11ea-8e1e-767ec603b8d6.jpg)

**Comment by kimbapslice** [comment] 2020-01-19 16:02
Earlier I did flash test1 twice as well. I have been trying to flash a build multiple times to exclude flashing/soldering errors.

**Comment by Xaranar** [comment] 2020-01-19 17:05
Looking promising, do you need me to test your earlier build of p2xh or do you have all the information you need from the wii dual builds?

**Comment by ikorb** [comment] 2020-01-19 19:28
@Xaranar: It would be helpful if you could test the p2xh build from [this post](https://github.com/ikorb/gcvideo/issues/26#issuecomment-575956426)

@kimbapslice: Yay, Heisenbugs. The attached X1 build should in theory be the same as the three-things-changed build linked previously, but it also includes the inverted color fix. The slow blinking is normal, I changed the blinking pattern (again...) to free up a bit of FPGA resources for the color fix.

[gcvideo-TEST_X1-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4083351/gcvideo-TEST_X1-dual-wii.zip)

**Comment by kimbapslice** [comment] 2020-01-19 19:39
X1 success! Booted into full color menu! Woohoo!
![IMG_20200119_143731809](https://user-images.githubusercontent.com/58018661/72687182-7e4c7980-3ac9-11ea-9d21-b354a4e1fcf9.jpg)
![IMG_20200119_143755700](https://user-images.githubusercontent.com/58018661/72687185-84daf100-3ac9-11ea-8d13-c70d3e9cce53.jpg)

**Comment by ikorb** [comment] 2020-01-19 19:46
Ok, I guess I should give up on the fast boot process for the Wii then. I have an idea why it works for me but not you, but I'm not going to tear down another Wii just to measure the power-up behaviour of a single signal.

Will build release 3.0b now, including all fixes from X1.

**Comment by kimbapslice** [comment] 2020-01-19 19:50
Thank you so much for your time and work! Maybe I can try the dol update process from the X1 test version?

**Comment by ikorb** [comment] 2020-01-19 19:52
You could, but then you would still have the countdown screen with the register dumps because the DOL update only updates the main firmware and not the flasher.

**Comment by ikorb** [comment] 2020-01-19 22:10
3.0b release is out, I really really really hope that this is now fixed.

**Comment by kimbapslice** [comment] 2020-01-19 22:37
Yes I was able to flash 3.0b and it booted successfully. So at this point any issues functionality wise is updatable via the dol? I will put the Wii together now :) thank you!

**Comment by ikorb** [comment] 2020-01-19 22:48
Yes, it should be updateable using the updater.dol now. Feel free to try it, the system won't prevent you from installing the same version again or even downgrading.

**Closed by ikorb** 2020-01-19 22:48 UTC
Labels: Wii, flasher
